// 播放显示的图标
export const PLAY_IMAGE_URL = 'app.media.miniplayer_bottom_play_2x';

// 暂停显示的图标
export const PAUSE_IMAGE_URL = 'app.media.miniplayer_bottom_pause_2x';

// 进度条滑块图标
export const KNOB_IMAGE_URL = 'app.media.fullplayer_progress_point_2x';

// Demo hilog的domain，复杂的App需要定义不同的值，我们只使用同一个值
export const LOG_DOMAIN = 0x0000;

// 进度条最大值
export const MAX_PROGRESS = 100;

// 进度条最小刻度值
export const PROGRESS_STEP = 0.05;

// 辅进度条的滑块颜色，透明
export const SLIDER_BLOCK_COLOR = 'rgba(0, 0, 0, 0.0)';

// 进度条背景色
export const SLIDER_TRACK_COLOR = 'rgba(128, 128, 128, 0.5)';

// 辅进度条的进度颜色
export const SLIDER_SELECTED_COLOR = 'rgba(160, 160, 160, 1.0)';

// 进度监控定制器时间间隔
export const PROGRESS_TIMER_INTERVAL_SEC = 0.5;

export const PAUSE_DOWNLOAD_TITLE = '暂停数据下载';

export const RESUME_DOWNLOAD_TITLE = '继续数据下载';